// The catalog of 100 hireable jobs.
//
// Each entry is a concrete deliverable an SMB can name in one breath. The
// jobs map 1:1 to the research brief on SMB use cases (see PR description).
//
// What's in an entry:
//   - id              stable slug for URLs and analytics
//   - function        which department it belongs to
//   - name            short, human, outcome-shaped name
//   - tagline         one-line "what you get" (display italic in the UI)
//   - killer          true if SMBs would pay $50–$500/mo without flinching
//   - trigger         when it runs (schedule / event / inbox / manual / threshold)
//   - sources         what it reads (1+ connectors)
//   - action          what it does (verb + plain-language description)
//   - output          where the result lands
//   - approval        default autonomy gate
//   - memory          what it remembers across runs
//   - sla             when results are needed
//   - priceMonthly    suggested subscription price band, in USD cents
//   - billingUnit     the "unit of value" we charge per accepted result
//   - heroPrompt      a synthesized prompt seed; the agent receives this on first run

import type {
  Action,
  Approval,
  Memory,
  Output,
  Source,
  Trigger,
} from "./primitives";
import type { FunctionId } from "./functions";

export interface JobBlueprint {
  id: string;
  function: FunctionId;
  name: string;
  tagline: string;
  killer: boolean;
  trigger: Trigger;
  sources: ReadonlyArray<Source>;
  action: Action;
  output: Output;
  approval: Approval;
  memory: Memory;
  sla: string;
  priceMonthly: number;
  billingUnit: string;
  heroPrompt: string;
}

const T = {
  daily: (at: string): Trigger => ({ kind: "schedule", cadence: `Every day at ${at}` }),
  weekly: (day: string, at: string): Trigger => ({
    kind: "schedule",
    cadence: `Every ${day} at ${at}`,
  }),
  monthly: (day: string, at: string): Trigger => ({
    kind: "schedule",
    cadence: `On the ${day} of each month at ${at}`,
  }),
  quarterly: (when: string): Trigger => ({
    kind: "schedule",
    cadence: `Quarterly — ${when}`,
  }),
  hourly: (): Trigger => ({ kind: "schedule", cadence: "Every hour" }),
  event: (signal: string): Trigger => ({ kind: "event", signal }),
  inbox: (signal: string): Trigger => ({ kind: "inbox", signal }),
  threshold: (predicate: string): Trigger => ({ kind: "threshold", predicate }),
  manual: (): Trigger => ({ kind: "manual" }),
};

const src = (category: Source["category"], connector: string, label?: string): Source => ({
  category,
  connector,
  ...(label ? { label } : {}),
});

const A = (verb: Action["verb"], description: string): Action => ({ verb, description });

const O = (kind: Output["kind"], target?: string): Output => ({
  kind,
  ...(target ? { target } : {}),
});

const APP = {
  draft: { kind: "draft-for-approval" } as Approval,
  auto: { kind: "autonomous" } as Approval,
  ask: { kind: "always-ask" } as Approval,
  gated: (threshold: number): Approval => ({ kind: "confidence-gated", threshold }),
};

const MEM = {
  stateless: { kind: "stateless" } as Memory,
  perTarget: (desc: string): Memory => ({ kind: "per-target", description: desc }),
  perJob: (desc: string): Memory => ({ kind: "per-job", description: desc }),
  org: (desc: string): Memory => ({ kind: "org-persistent", description: desc }),
};

/* ============================== SALES (10) ============================== */
const SALES: JobBlueprint[] = [
  {
    id: "sales-icp-prospecting",
    function: "sales",
    name: "Outbound prospecting on an ICP",
    tagline: "50 fresh ICP-matched companies every week, enriched with a why-now signal.",
    killer: true,
    trigger: T.weekly("Monday", "07:00"),
    sources: [src("web", "apollo"), src("web", "linkedin"), src("crm", "hubspot")],
    action: A("research", "Find 50 companies matching the ICP, enrich with funding / headcount / tech-stack signals, score, attach a why-now line."),
    output: O("table", "Google Sheet · ICP-weekly"),
    approval: APP.draft,
    memory: MEM.perTarget("Skip companies already reached in the last 90 days."),
    sla: "Land by Monday 8:00 AM operator time.",
    priceMonthly: 29900,
    billingUnit: "per qualified lead delivered",
    heroPrompt: "Pull 50 companies matching our ICP each Monday morning. Enrich with funding, headcount, tech stack. Add a one-line 'why now' for each. Skip anyone we've already reached in the past 90 days.",
  },
  {
    id: "sales-inbound-triage",
    function: "sales",
    name: "Inbound lead triage & routing",
    tagline: "Every form submission scored, summarized, and posted to #sales-hot with a draft reply.",
    killer: true,
    trigger: T.event("hubspot.form.submitted"),
    sources: [src("crm", "hubspot"), src("inbox", "gmail")],
    action: A("classify", "Score new leads against the ICP, summarize in 5 lines, draft a personalized first reply."),
    output: O("slack", "#sales-hot"),
    approval: APP.draft,
    memory: MEM.perTarget("Remember each lead's history with us."),
    sla: "Posted within 5 minutes of submission.",
    priceMonthly: 19900,
    billingUnit: "per triaged lead",
    heroPrompt: "When a HubSpot form is submitted or an inbound email lands, score against ICP, summarize, draft a personalized first reply, and post the package to #sales-hot.",
  },
  {
    id: "sales-no-show-recovery",
    function: "sales",
    name: "Demo no-show recovery",
    tagline: "Sympathetic reschedule drafts for every missed call.",
    killer: false,
    trigger: T.event("gcal.event.missed"),
    sources: [src("calendar", "gcal"), src("crm", "hubspot")],
    action: A("draft", "Detect missed sales calls, draft a sympathetic reschedule referencing the original meeting purpose."),
    output: O("email-draft", "rep's drafts folder"),
    approval: APP.draft,
    memory: MEM.perTarget("Track no-show counts per prospect."),
    sla: "Within 1 hour of the missed call.",
    priceMonthly: 7900,
    billingUnit: "per reschedule recovered",
    heroPrompt: "When a sales call gets a no-show, draft a sympathetic reschedule referencing the meeting's original purpose.",
  },
  {
    id: "sales-personalized-first-touch",
    function: "sales",
    name: "Personalized first-touch drafting",
    tagline: "Per-prospect research + 3 first-touch variants for human approval.",
    killer: true,
    trigger: T.manual(),
    sources: [src("web", "linkedin"), src("web", "crunchbase"), src("crm", "hubspot")],
    action: A("draft", "Research each prospect (recent press, role tenure, company news), produce 3 first-touch variants."),
    output: O("table", "Google Sheet · first-touch drafts"),
    approval: APP.draft,
    memory: MEM.perTarget("Don't repeat angles you've already drafted for this prospect."),
    sla: "Within 10 minutes per prospect.",
    priceMonthly: 24900,
    billingUnit: "per draft set delivered",
    heroPrompt: "Given a prospect, research recent press, role tenure, and company news. Produce three first-touch variants with distinct angles, ready for sales rep approval.",
  },
  {
    id: "sales-crm-hygiene",
    function: "sales",
    name: "CRM hygiene weekly sweep",
    tagline: "Stale deals, missing close-dates, and duplicate contacts flagged for cleanup.",
    killer: false,
    trigger: T.weekly("Friday", "16:00"),
    sources: [src("crm", "hubspot")],
    action: A("reconcile", "Sweep for stale deals (>30 days no activity), missing close dates, duplicate contacts; deliver a remediation table."),
    output: O("memo", "Friday cleanup memo"),
    approval: APP.draft,
    memory: MEM.perJob("Track which items were fixed week over week."),
    sla: "Delivered Friday by 5:00 PM.",
    priceMonthly: 9900,
    billingUnit: "per remediation item surfaced",
    heroPrompt: "Sweep HubSpot weekly for stale deals (no activity >30 days), missing close dates, and duplicate contacts. Produce a remediation table.",
  },
  {
    id: "sales-pipeline-standup",
    function: "sales",
    name: "Monday pipeline briefing",
    tagline: "One-page memo: what slipped, what advanced, what's at risk, what to call.",
    killer: false,
    trigger: T.weekly("Monday", "08:00"),
    sources: [src("crm", "hubspot")],
    action: A("summarize", "Produce a one-page memo: deals slipped, deals advanced, deals at risk, suggested calls."),
    output: O("memo", "Monday standup doc"),
    approval: APP.auto,
    memory: MEM.perJob("Compare against last week's pipeline state."),
    sla: "Land by Monday 8:00 AM.",
    priceMonthly: 12900,
    billingUnit: "per weekly memo",
    heroPrompt: "Every Monday at 8 AM, produce a one-page pipeline memo: deals that slipped, advanced, are at risk, and the 3 calls the sales lead should prioritize.",
  },
  {
    id: "sales-competitor-mentions",
    function: "sales",
    name: "Competitor mention monitor",
    tagline: "Daily digest of G2 / Reddit / HN / Twitter mentions with sentiment.",
    killer: false,
    trigger: T.daily("09:00"),
    sources: [src("web", "web"), src("web", "rss")],
    action: A("monitor", "Watch G2, Reddit, HN, and Twitter for competitor names; tag sentiment; flag 'lost to X' mentions."),
    output: O("memo", "Daily competitive intel digest"),
    approval: APP.auto,
    memory: MEM.perJob("Track sentiment trends per competitor."),
    sla: "Daily 9:00 AM digest.",
    priceMonthly: 14900,
    billingUnit: "per relevant mention",
    heroPrompt: "Watch G2, Reddit, HN, and Twitter for our competitors. Tag sentiment. Flag every 'lost to X' mention. Daily digest at 9 AM.",
  },
  {
    id: "sales-renewal-radar",
    function: "sales",
    name: "Renewal & expansion radar",
    tagline: "Weekly at-risk list with usage drops, late invoices, and ticket spikes.",
    killer: false,
    trigger: T.weekly("Monday", "07:30"),
    sources: [src("crm", "hubspot"), src("finance", "stripe"), src("inbox", "zendesk"), src("telemetry", "mixpanel")],
    action: A("monitor", "For each customer, flag usage drops, late invoices, support spikes; produce a weekly at-risk list."),
    output: O("table", "Renewal-radar sheet"),
    approval: APP.auto,
    memory: MEM.perTarget("Track each customer's risk trajectory."),
    sla: "Monday by 8:00 AM.",
    priceMonthly: 19900,
    billingUnit: "per at-risk account flagged",
    heroPrompt: "Every Monday morning, cross-reference HubSpot, Stripe, Zendesk, and Mixpanel. Flag any customer with usage drops, late invoices, or support spikes. Output a sorted at-risk table.",
  },
  {
    id: "sales-rfp-firstdraft",
    function: "sales",
    name: "RFP & security questionnaire first-draft",
    tagline: "70% of any vendor questionnaire auto-filled from prior answers.",
    killer: true,
    trigger: T.manual(),
    sources: [src("files", "xlsx"), src("productivity", "gdocs"), src("productivity", "notion")],
    action: A("draft", "Match each question to our prior-answer knowledge base, auto-fill where confident, flag the rest for human input."),
    output: O("memo", "RFP draft + open-questions list"),
    approval: APP.draft,
    memory: MEM.org("Curates our growing answer playbook."),
    sla: "Within 24 hours.",
    priceMonthly: 39900,
    billingUnit: "per questionnaire processed",
    heroPrompt: "When given a vendor RFP or security questionnaire, match each question to our knowledge base, auto-fill at high confidence, and flag the rest for human input.",
  },
  {
    id: "sales-lost-deal-letter",
    function: "sales",
    name: "Lost-deal post-mortem letter",
    tagline: "Short, sincere request for one specific piece of feedback.",
    killer: false,
    trigger: T.event("hubspot.deal.closed-lost"),
    sources: [src("crm", "hubspot")],
    action: A("draft", "Draft a short note asking for one specific piece of feedback. Route reply into the lost-deal learnings doc."),
    output: O("email-draft", "rep's drafts folder"),
    approval: APP.draft,
    memory: MEM.perJob("Aggregate themes across lost deals."),
    sla: "Within 2 hours of close-lost.",
    priceMonthly: 6900,
    billingUnit: "per letter drafted",
    heroPrompt: "When a deal closes lost, draft a short, sincere note asking the buyer for one specific piece of feedback. Route their reply into a shared learnings doc.",
  },
];

/* ============================ MARKETING (10) ============================ */
const MARKETING: JobBlueprint[] = [
  {
    id: "mkt-content-ideation",
    function: "marketing",
    name: "Weekly content topic ideation",
    tagline: "10 blog/LinkedIn topics ranked by demand evidence — not vibes.",
    killer: true,
    trigger: T.weekly("Monday", "07:00"),
    sources: [src("web", "rss"), src("inbox", "zendesk"), src("chat", "slack")],
    action: A("cluster", "Scrape r/<industry>, support tickets, and sales-call transcripts; produce 10 topics ranked by demand evidence."),
    output: O("memo", "Weekly content brief"),
    approval: APP.auto,
    memory: MEM.perJob("Avoid repeating last 4 weeks of topics."),
    sla: "Monday 8:00 AM.",
    priceMonthly: 19900,
    billingUnit: "per topic delivered",
    heroPrompt: "Every Monday, scrape relevant subreddits, our support tickets, and recent sales-call transcripts. Cluster into 10 ranked content topics with evidence per item.",
  },
  {
    id: "mkt-repurposing",
    function: "marketing",
    name: "Blog → everywhere repurposing",
    tagline: "One long-form post → carousel, thread, newsletter, short script — queued for approval.",
    killer: true,
    trigger: T.event("ghost.post.published"),
    sources: [src("web", "url"), src("productivity", "gdocs")],
    action: A("draft", "Produce a LinkedIn carousel, an X thread, a newsletter blurb, and a YouTube short script from one post."),
    output: O("table", "Buffer queue · draft"),
    approval: APP.draft,
    memory: MEM.org("Stays in the brand voice and visual system."),
    sla: "Within 2 hours of post publish.",
    priceMonthly: 24900,
    billingUnit: "per repurposed artifact",
    heroPrompt: "When a new long-form post publishes, produce a LinkedIn carousel, an X thread, a newsletter blurb, and a YouTube Short script. Queue them in Buffer for approval.",
  },
  {
    id: "mkt-seo-briefs",
    function: "marketing",
    name: "SEO content brief generation",
    tagline: "Target keyword → SERP analysis + H2 outline + FAQ schema + internal links.",
    killer: false,
    trigger: T.manual(),
    sources: [src("web", "web"), src("productivity", "gdocs")],
    action: A("research", "Pick a keyword cluster, pull the top 10 SERPs, deliver a brief with H2 outline, FAQ schema, and internal-link suggestions."),
    output: O("memo", "SEO brief"),
    approval: APP.auto,
    memory: MEM.org("Knows our existing content inventory."),
    sla: "Within 30 minutes.",
    priceMonthly: 14900,
    billingUnit: "per brief generated",
    heroPrompt: "Given a target keyword, pull the top 10 SERPs, produce an H2 outline, FAQ schema suggestions, and internal-link targets from our existing content.",
  },
  {
    id: "mkt-newsletter",
    function: "marketing",
    name: "Newsletter assembly",
    tagline: "The week's posts + customer wins + one industry story, ready to review.",
    killer: false,
    trigger: T.weekly("Thursday", "10:00"),
    sources: [src("web", "rss"), src("chat", "slack"), src("web", "url")],
    action: A("draft", "Pull the week's posts, wins from #wins, and one industry story; draft the newsletter."),
    output: O("email-draft", "Beehiiv draft"),
    approval: APP.draft,
    memory: MEM.org("Keeps voice consistent week to week."),
    sla: "Thursday by 11:00 AM.",
    priceMonthly: 14900,
    billingUnit: "per newsletter draft",
    heroPrompt: "Each Thursday morning, pull the week's blog posts, customer wins from #wins, and one industry story. Draft the newsletter in our voice for the founder to review.",
  },
  {
    id: "mkt-review-harvest",
    function: "marketing",
    name: "Review & testimonial harvest",
    tagline: "Positive reviews → quote-request drafts; negative → founder alerts with triage.",
    killer: true,
    trigger: T.event("g2.review.new"),
    sources: [src("web", "g2"), src("web", "url")],
    action: A("classify", "Triage every new review; draft thank-you + quote-request for positive, alert founder with triage for negative."),
    output: O("slack", "#brand"),
    approval: APP.draft,
    memory: MEM.perTarget("Track each reviewer's history."),
    sla: "Within 2 hours of review post.",
    priceMonthly: 12900,
    billingUnit: "per review handled",
    heroPrompt: "Monitor G2, Capterra, and Google Reviews. On positive reviews, draft a thank-you + quote-permission ask. On negative, alert the founder with a triage suggestion.",
  },
  {
    id: "mkt-ad-variants",
    function: "marketing",
    name: "Paid-ad creative variations",
    tagline: "One winning ad → 8 hook/headline/visual variants with predicted angle.",
    killer: false,
    trigger: T.manual(),
    sources: [src("productivity", "gdocs"), src("web", "url")],
    action: A("draft", "Produce 8 hook/headline/visual-prompt variants for Meta/Google testing with an angle per variant."),
    output: O("table", "Ad-test plan sheet"),
    approval: APP.draft,
    memory: MEM.org("Remembers what's already been tested."),
    sla: "Within 1 hour.",
    priceMonthly: 14900,
    billingUnit: "per variant set",
    heroPrompt: "Given one winning ad, produce 8 hook/headline/visual variants for Meta and Google testing. Predict the angle for each.",
  },
  {
    id: "mkt-event-sourcing",
    function: "marketing",
    name: "Conference & event sourcing",
    tagline: "5 events/month matching ICP & budget — with sponsorship math.",
    killer: false,
    trigger: T.monthly("1st", "09:00"),
    sources: [src("web", "web")],
    action: A("research", "Scan event calendars; identify 5 matching ICP and budget; deliver go/no-go memos with sponsorship math."),
    output: O("memo", "Monthly events memo"),
    approval: APP.auto,
    memory: MEM.perJob("Don't repeat events we already evaluated."),
    sla: "By the 2nd of each month.",
    priceMonthly: 17900,
    billingUnit: "per event memo",
    heroPrompt: "Each month, scan Eventbrite, Lu.ma, and industry calendars. Pick 5 events matching our ICP and budget. Produce a go/no-go memo with sponsorship cost math.",
  },
  {
    id: "mkt-webinar-followup",
    function: "marketing",
    name: "Webinar follow-up sequencing",
    tagline: "Segmented follow-ups: attended + engaged / attended silent / no-show.",
    killer: false,
    trigger: T.event("webinar.ended"),
    sources: [src("crm", "hubspot"), src("calendar", "calendly")],
    action: A("draft", "Segment attendees by engagement; draft 3 different follow-up emails."),
    output: O("email-draft", "marketing drafts"),
    approval: APP.draft,
    memory: MEM.perTarget("Don't double-message someone in multiple segments."),
    sla: "Within 4 hours of webinar end.",
    priceMonthly: 12900,
    billingUnit: "per webinar handled",
    heroPrompt: "Post-webinar, segment attendees into 'engaged', 'silent', and 'no-show'. Draft 3 different follow-up emails for each segment.",
  },
  {
    id: "mkt-press-monitor",
    function: "marketing",
    name: "Press monitoring",
    tagline: "Daily scan of trade pubs for mentions + reply-or-ignore suggestion.",
    killer: false,
    trigger: T.daily("08:00"),
    sources: [src("web", "rss"), src("web", "web")],
    action: A("monitor", "Daily scan of trade publications for company mentions, industry shifts, and PR openings."),
    output: O("slack", "#press"),
    approval: APP.auto,
    memory: MEM.perJob("Don't double-flag the same mention."),
    sla: "Daily 8:00 AM.",
    priceMonthly: 11900,
    billingUnit: "per relevant mention",
    heroPrompt: "Daily scan of trade publications and PR feeds. Surface any mention of our company, industry shifts, or PR opportunities. Reply-or-ignore suggestion per item.",
  },
  {
    id: "mkt-social-listening",
    function: "marketing",
    name: "Social listening for product feedback",
    tagline: "Reddit/Twitter/Discord mentions → categorized into roadmap themes.",
    killer: false,
    trigger: T.weekly("Friday", "15:00"),
    sources: [src("web", "rss"), src("chat", "discord")],
    action: A("cluster", "Aggregate weekly mentions, categorize by feature, file into the roadmap doc."),
    output: O("memo", "Weekly social-listening memo"),
    approval: APP.auto,
    memory: MEM.perJob("Track theme trajectory over time."),
    sla: "Friday by 4:00 PM.",
    priceMonthly: 13900,
    billingUnit: "per theme surfaced",
    heroPrompt: "Each Friday, aggregate Reddit, Twitter, and Discord mentions of our product. Cluster by feature. File into the product roadmap doc with quote excerpts.",
  },
];

/* ====================== CUSTOMER SUCCESS (10) =========================== */
const CS: JobBlueprint[] = [
  {
    id: "cs-ticket-triage",
    function: "cs",
    name: "Support ticket triage & first-draft reply",
    tagline: "Every ticket categorized, tagged, prioritized, and replied to in under 2 minutes.",
    killer: true,
    trigger: T.event("zendesk.ticket.created"),
    sources: [src("inbox", "zendesk")],
    action: A("classify", "Categorize, tag, prioritize. Draft an initial reply for human approval."),
    output: O("ticket", "Zendesk · draft reply attached"),
    approval: APP.draft,
    memory: MEM.perTarget("Knows each customer's history."),
    sla: "Within 2 minutes of ticket creation.",
    priceMonthly: 24900,
    billingUnit: "per triaged ticket",
    heroPrompt: "When a new Zendesk ticket arrives, categorize, tag, prioritize, and draft an initial reply within 2 minutes for the agent to review.",
  },
  {
    id: "cs-onboarding-stuck",
    function: "cs",
    name: "Onboarding-stuck detection",
    tagline: "Stalled new accounts get a tailored unblock email referencing what they did.",
    killer: true,
    trigger: T.threshold("Onboarding step unchanged for 48 hours"),
    sources: [src("telemetry", "mixpanel"), src("crm", "hubspot")],
    action: A("draft", "Detect stalled onboarding; draft a tailored unblock email referencing completed steps."),
    output: O("email-draft", "CSM's drafts"),
    approval: APP.draft,
    memory: MEM.perTarget("Track unblock attempts."),
    sla: "Within 1 hour of threshold trip.",
    priceMonthly: 17900,
    billingUnit: "per stalled account caught",
    heroPrompt: "Watch onboarding telemetry. When a new account hasn't progressed for 48 hours, draft a tailored unblock email naming what they completed and what's left.",
  },
  {
    id: "cs-nps-followup",
    function: "cs",
    name: "NPS / CSAT follow-ups",
    tagline: "Detractor outreach + promoter referral/quote asks, automatically drafted.",
    killer: false,
    trigger: T.event("nps.response.received"),
    sources: [src("telemetry", "mixpanel"), src("crm", "hubspot")],
    action: A("draft", "Draft detractor outreach asking 'what would we need to change'; draft promoter referral/quote requests."),
    output: O("email-draft", "CSM drafts"),
    approval: APP.draft,
    memory: MEM.perTarget("Track NPS history per account."),
    sla: "Within 4 hours.",
    priceMonthly: 9900,
    billingUnit: "per follow-up drafted",
    heroPrompt: "When an NPS or CSAT response arrives, draft outreach: detractors get 'what would we need to change' asks; promoters get referral or quote requests.",
  },
  {
    id: "cs-health-digest",
    function: "cs",
    name: "Account health weekly digest",
    tagline: "Per-CSM Monday memo: usage, billing, tickets, sentiment — ranked by priority.",
    killer: true,
    trigger: T.weekly("Monday", "07:30"),
    sources: [src("telemetry", "mixpanel"), src("finance", "stripe"), src("inbox", "zendesk"), src("crm", "hubspot")],
    action: A("summarize", "For each CSM's book, summarize usage trends, billing changes, open tickets, sentiment — ranked by intervention priority."),
    output: O("memo", "Per-CSM Monday memo"),
    approval: APP.auto,
    memory: MEM.perTarget("Track each account's trajectory."),
    sla: "Monday by 8:00 AM.",
    priceMonthly: 22900,
    billingUnit: "per CSM book covered",
    heroPrompt: "Each Monday, per CSM: produce a memo of their book ranked by intervention priority — usage trend, billing changes, open tickets, sentiment.",
  },
  {
    id: "cs-churn-save",
    function: "cs",
    name: "Churn-risk save plays",
    tagline: "Downgrades, cancellation flows, usage cliffs → save email + scheduled call.",
    killer: false,
    trigger: T.event("stripe.subscription.downgraded"),
    sources: [src("finance", "stripe"), src("telemetry", "mixpanel"), src("crm", "hubspot")],
    action: A("coordinate", "Draft a save email and schedule a call with the right rep on detected churn signals."),
    output: O("ticket", "CRM · save play"),
    approval: APP.draft,
    memory: MEM.perTarget("Track save attempts and outcomes."),
    sla: "Within 1 hour of trigger.",
    priceMonthly: 19900,
    billingUnit: "per save play queued",
    heroPrompt: "When a customer downgrades, opens cancellation, or hits a usage cliff, draft a save email and book a call with the right rep.",
  },
  {
    id: "cs-kb-gaps",
    function: "cs",
    name: "Knowledge-base gap detection",
    tagline: "Monthly: 5 new KB drafts from tickets that had no matching article.",
    killer: false,
    trigger: T.monthly("1st", "09:00"),
    sources: [src("inbox", "zendesk"), src("productivity", "notion")],
    action: A("cluster", "Cluster tickets with no matching KB article; draft 5 new articles."),
    output: O("memo", "Monthly KB-draft batch"),
    approval: APP.draft,
    memory: MEM.org("Knows our existing KB to avoid duplicates."),
    sla: "By the 2nd of each month.",
    priceMonthly: 12900,
    billingUnit: "per article drafted",
    heroPrompt: "Once a month, cluster support tickets that had no matching KB article. Draft 5 new articles for human edit.",
  },
  {
    id: "cs-qbr-prep",
    function: "cs",
    name: "Quarterly business review prep",
    tagline: "Per tier-1 account: usage, ROI, roadmap, expansion ideas in a draft deck.",
    killer: false,
    trigger: T.quarterly("two weeks before QBR"),
    sources: [src("telemetry", "mixpanel"), src("crm", "hubspot"), src("productivity", "gdocs")],
    action: A("draft", "Assemble a QBR deck: usage, ROI, roadmap, expansion ideas."),
    output: O("memo", "QBR deck draft"),
    approval: APP.draft,
    memory: MEM.perTarget("Knows each account's last QBR."),
    sla: "Two weeks before the QBR date.",
    priceMonthly: 24900,
    billingUnit: "per account deck",
    heroPrompt: "For each tier-1 account, two weeks before their QBR, assemble a draft deck covering usage, ROI, roadmap, and expansion ideas.",
  },
  {
    id: "cs-user-research",
    function: "cs",
    name: "User interview recruit & synthesis",
    tagline: "Find candidates, schedule via Calendly, transcribe, synthesize into a memo.",
    killer: false,
    trigger: T.manual(),
    sources: [src("crm", "hubspot"), src("calendar", "calendly"), src("files", "loom")],
    action: A("coordinate", "Recruit users matching a segment; schedule; transcribe; synthesize a memo."),
    output: O("memo", "Research synthesis"),
    approval: APP.draft,
    memory: MEM.perJob("Don't re-recruit the same users."),
    sla: "Initial recruit within 48 hours.",
    priceMonthly: 19900,
    billingUnit: "per completed interview cycle",
    heroPrompt: "Given a user segment, recruit matching candidates from our CRM and product telemetry. Schedule via Calendly. Post-call, transcribe and synthesize into a research memo.",
  },
  {
    id: "cs-renewal-prep",
    function: "cs",
    name: "Renewal prep package",
    tagline: "60-day-out usage report + exec summary + pricing options + draft email.",
    killer: false,
    trigger: T.threshold("Renewal due in 60 days"),
    sources: [src("finance", "stripe"), src("telemetry", "mixpanel"), src("crm", "hubspot")],
    action: A("draft", "Assemble usage report, exec summary, pricing options, and a draft renewal email."),
    output: O("memo", "Renewal package"),
    approval: APP.draft,
    memory: MEM.perTarget("Knows each account's prior renewal."),
    sla: "60 days before renewal.",
    priceMonthly: 21900,
    billingUnit: "per renewal packaged",
    heroPrompt: "Sixty days before any renewal, assemble: usage report, exec summary, pricing options, and a draft renewal email.",
  },
  {
    id: "cs-sla-breach",
    function: "cs",
    name: "SLA breach alerting",
    tagline: "Tickets approaching SLA limits → owner alert + escalation suggestion.",
    killer: false,
    trigger: T.threshold("Ticket SLA at 80% of budget"),
    sources: [src("inbox", "zendesk")],
    action: A("monitor", "Watch queues; alert owning agent when SLA is at 80%; suggest escalation."),
    output: O("slack", "@owner DM"),
    approval: APP.auto,
    memory: MEM.stateless,
    sla: "Real-time.",
    priceMonthly: 8900,
    billingUnit: "per alert sent",
    heroPrompt: "Watch the ticket queue. Alert the owning agent via Slack DM when any ticket is at 80% of its response or resolution SLA. Suggest the right escalation.",
  },
];

/* ============================ OPERATIONS (10) =========================== */
const OPS: JobBlueprint[] = [
  {
    id: "ops-monday-dashboard",
    function: "ops",
    name: "Monday state-of-the-business memo",
    tagline: "1-page KPI memo across Stripe / HubSpot / Mixpanel / QuickBooks / support.",
    killer: true,
    trigger: T.weekly("Monday", "06:30"),
    sources: [src("finance", "stripe"), src("crm", "hubspot"), src("telemetry", "mixpanel"), src("finance", "quickbooks"), src("inbox", "zendesk")],
    action: A("summarize", "Pull KPIs from every system and produce a 1-page Monday memo."),
    output: O("memo", "State of the business · Monday"),
    approval: APP.auto,
    memory: MEM.perJob("Highlight what changed week over week."),
    sla: "Monday by 7:00 AM.",
    priceMonthly: 24900,
    billingUnit: "per weekly memo",
    heroPrompt: "Every Monday morning, pull KPIs from Stripe, HubSpot, Mixpanel, QuickBooks, and support. Produce a 1-page memo with what changed.",
  },
  {
    id: "ops-invoice-recon",
    function: "ops",
    name: "Vendor invoice reconciliation",
    tagline: "Match PDFs to POs/contracts, flag discrepancies, queue clean ones.",
    killer: false,
    trigger: T.inbox("accounting@ — new PDF attachment"),
    sources: [src("inbox", "gmail"), src("files", "pdf"), src("finance", "quickbooks")],
    action: A("reconcile", "Match incoming PDFs to PO/contract records, flag discrepancies, queue clean ones for approval."),
    output: O("ticket", "QuickBooks · pending approval"),
    approval: APP.draft,
    memory: MEM.perTarget("Knows each vendor's billing patterns."),
    sla: "Within 1 hour of email arrival.",
    priceMonthly: 17900,
    billingUnit: "per invoice processed",
    heroPrompt: "When a vendor invoice PDF lands in accounting@, match it against POs and contracts. Flag discrepancies. Queue clean ones for approval.",
  },
  {
    id: "ops-procurement",
    function: "ops",
    name: "Procurement research",
    tagline: "5 candidate tools with pricing/features/pros-cons/demo links.",
    killer: false,
    trigger: T.manual(),
    sources: [src("web", "web")],
    action: A("research", "Given a tool category and constraints, produce a shortlist of 5 with pricing, features, pros/cons, demo links."),
    output: O("memo", "Procurement shortlist"),
    approval: APP.auto,
    memory: MEM.stateless,
    sla: "Within 2 hours.",
    priceMonthly: 9900,
    billingUnit: "per shortlist delivered",
    heroPrompt: "Given a tool category and constraints (budget, must-integrate-with), produce a shortlist of 5 with pricing, features, pros/cons, and demo links.",
  },
  {
    id: "ops-sop-maintenance",
    function: "ops",
    name: "SOP drafting & maintenance",
    tagline: "Loom or interview → Notion SOP; tool changes → flag SOPs for refresh.",
    killer: false,
    trigger: T.manual(),
    sources: [src("files", "loom"), src("productivity", "notion")],
    action: A("draft", "Produce a Notion SOP page from a Loom or interview. Flag SOPs that drift when linked tools change."),
    output: O("memo", "SOP page draft"),
    approval: APP.draft,
    memory: MEM.org("Tracks SOP drift across the library."),
    sla: "Within 24 hours of source upload.",
    priceMonthly: 11900,
    billingUnit: "per SOP drafted",
    heroPrompt: "Given a Loom recording or interview, produce a Notion SOP page. When linked tools change, flag SOPs needing refresh.",
  },
  {
    id: "ops-hiring-inbox",
    function: "ops",
    name: "Hiring inbox triage",
    tagline: "Greenhouse applicants scored, screened, scheduled (or politely declined).",
    killer: true,
    trigger: T.event("greenhouse.application.received"),
    sources: [src("people", "greenhouse"), src("calendar", "gcal")],
    action: A("classify", "Score applicants against the JD; draft invites or polite declines; schedule screens with the hiring manager."),
    output: O("ticket", "Greenhouse · stage advance"),
    approval: APP.draft,
    memory: MEM.perTarget("Don't re-screen recently rejected candidates."),
    sla: "Within 24 hours of application.",
    priceMonthly: 21900,
    billingUnit: "per applicant triaged",
    heroPrompt: "When a new Greenhouse application arrives, score against the JD. Draft a first-screen invite or polite decline. Schedule screens with the hiring manager's calendar.",
  },
  {
    id: "ops-offboarding",
    function: "ops",
    name: "Equipment & access offboarding",
    tagline: "Termination event → checklist: accounts off, laptop recovery, drive transfer.",
    killer: false,
    trigger: T.event("rippling.employee.terminated"),
    sources: [src("people", "rippling"), src("productivity", "github"), src("chat", "slack")],
    action: A("coordinate", "Generate offboarding ticket: disable accounts, recover laptop, transfer drives, revoke tokens."),
    output: O("ticket", "Asana · offboarding checklist"),
    approval: APP.ask,
    memory: MEM.stateless,
    sla: "Within 1 hour of termination event.",
    priceMonthly: 9900,
    billingUnit: "per offboarding completed",
    heroPrompt: "When an employee is terminated in Rippling, generate the offboarding checklist: disable all accounts, recover laptop, transfer Google Drive, revoke API tokens.",
  },
  {
    id: "ops-compliance-tracking",
    function: "ops",
    name: "Insurance & compliance cert tracking",
    tagline: "30-day-out renewal alerts with the right contact and draft request.",
    killer: false,
    trigger: T.daily("06:00"),
    sources: [src("files", "pdf"), src("productivity", "notion")],
    action: A("monitor", "Watch COI/BAA/DPA expiry; alert 30 days out with the contact and draft request."),
    output: O("email-draft", "ops drafts"),
    approval: APP.draft,
    memory: MEM.perTarget("Knows each cert's renewal cadence."),
    sla: "30 days before expiry.",
    priceMonthly: 7900,
    billingUnit: "per renewal handled",
    heroPrompt: "Monitor expiry dates of COI, BAA, DPA documents. Alert 30 days before expiry with the right contact and a draft renewal request.",
  },
  {
    id: "ops-status-page",
    function: "ops",
    name: "Status-page updates",
    tagline: "Incident detected → public status update + post-mortem first-draft.",
    killer: false,
    trigger: T.event("monitoring.incident.opened"),
    sources: [src("chat", "slack"), src("web", "url")],
    action: A("draft", "Draft and post a status update. Follow up with a post-mortem first-draft after resolution."),
    output: O("memo", "Status-page + post-mortem"),
    approval: APP.draft,
    memory: MEM.perJob("Maintains incident history."),
    sla: "Initial post within 5 minutes of incident.",
    priceMonthly: 14900,
    billingUnit: "per incident handled",
    heroPrompt: "When monitoring detects an incident, draft and post a status update. After resolution, draft the post-mortem.",
  },
  {
    id: "ops-people-logistics",
    function: "ops",
    name: "People logistics & moments",
    tagline: "Birthdays, anniversaries, welcome kits, holiday calendar drafts.",
    killer: false,
    trigger: T.weekly("Monday", "08:30"),
    sources: [src("people", "rippling"), src("calendar", "gcal")],
    action: A("coordinate", "Draft messages and orders for birthdays, anniversaries, new-hire welcome kits, holiday plans."),
    output: O("memo", "Weekly people-moments memo"),
    approval: APP.draft,
    memory: MEM.perTarget("Don't repeat last year's gift."),
    sla: "Monday morning.",
    priceMonthly: 7900,
    billingUnit: "per moment handled",
    heroPrompt: "Each Monday, surface team birthdays, anniversaries, and new-hire welcome moments for the week. Draft messages and orders.",
  },
  {
    id: "ops-data-sync-audit",
    function: "ops",
    name: "Cross-tool data sync audit",
    tagline: "Weekly: HubSpot ↔ Stripe ↔ ledger reconciliation; flag mismatches.",
    killer: true,
    trigger: T.weekly("Friday", "17:00"),
    sources: [src("crm", "hubspot"), src("finance", "stripe"), src("finance", "quickbooks")],
    action: A("reconcile", "Verify HubSpot ↔ Stripe ↔ ledger consistency; flag accounts in one but not the others."),
    output: O("table", "Weekly sync-audit sheet"),
    approval: APP.auto,
    memory: MEM.perJob("Remember accounts already flagged."),
    sla: "Friday by 6:00 PM.",
    priceMonthly: 17900,
    billingUnit: "per mismatch surfaced",
    heroPrompt: "Each Friday afternoon, reconcile HubSpot, Stripe, and the ledger. Flag any account that exists in one but not the others.",
  },
];

/* ============================== FINANCE (10) ============================ */
const FINANCE: JobBlueprint[] = [
  {
    id: "fin-ar-collections",
    function: "finance",
    name: "AR collections follow-ups",
    tagline: "Past-due invoices → personalized dunning sequence with escalation.",
    killer: true,
    trigger: T.threshold("Stripe invoice 1+ days past due"),
    sources: [src("finance", "stripe"), src("finance", "quickbooks"), src("crm", "hubspot")],
    action: A("draft", "Personalized dunning sequence (gentle → firm → escalate to founder), tracked per customer."),
    output: O("email-draft", "finance drafts"),
    approval: APP.draft,
    memory: MEM.perTarget("Track each customer's dunning history."),
    sla: "Drafts within 4 hours of past-due.",
    priceMonthly: 29900,
    billingUnit: "per dollar collected",
    heroPrompt: "When a Stripe or QuickBooks invoice goes past due, run a personalized dunning sequence: gentle → firm → escalate. Track per customer; never double-send.",
  },
  {
    id: "fin-close-prep",
    function: "finance",
    name: "Monthly close prep",
    tagline: "Bank feeds categorized, cards reconciled, 'anything weird?' report ready.",
    killer: true,
    trigger: T.monthly("3rd", "08:00"),
    sources: [src("finance", "quickbooks"), src("finance", "stripe"), src("finance", "ramp")],
    action: A("reconcile", "Pull bank feeds, categorize transactions, reconcile cards, deliver an 'anything weird?' report."),
    output: O("memo", "Close prep package"),
    approval: APP.draft,
    memory: MEM.org("Knows our chart of accounts."),
    sla: "By the 5th of each month.",
    priceMonthly: 34900,
    billingUnit: "per close cycle",
    heroPrompt: "Each month-close, pull bank feeds, categorize uncategorized transactions, reconcile cards, and deliver an 'anything weird?' report to the bookkeeper.",
  },
  {
    id: "fin-rev-rec",
    function: "finance",
    name: "Revenue recognition audit",
    tagline: "Each closed-won deal verified against Stripe subscription terms.",
    killer: false,
    trigger: T.event("hubspot.deal.closed-won"),
    sources: [src("crm", "hubspot"), src("finance", "stripe")],
    action: A("reconcile", "Verify the Stripe subscription matches the contract terms; flag mismatches."),
    output: O("alert", "finance Slack DM"),
    approval: APP.auto,
    memory: MEM.perTarget("Track each deal's contract terms."),
    sla: "Within 1 hour of close-won.",
    priceMonthly: 12900,
    billingUnit: "per mismatch caught",
    heroPrompt: "When a deal closes won, verify the Stripe subscription matches the contract terms (price, term, seats, start date). Flag any mismatch.",
  },
  {
    id: "fin-cash-forecast",
    function: "finance",
    name: "Cash-flow weekly forecast",
    tagline: "13-week rolling projection from AR, AP, payroll, contracts.",
    killer: false,
    trigger: T.weekly("Monday", "08:00"),
    sources: [src("finance", "stripe"), src("finance", "quickbooks"), src("finance", "ramp")],
    action: A("summarize", "Produce a 13-week rolling cash projection from current AR/AP, payroll, and known contracts."),
    output: O("memo", "Cash forecast"),
    approval: APP.auto,
    memory: MEM.perJob("Compare this week's forecast to last."),
    sla: "Monday by 9:00 AM.",
    priceMonthly: 21900,
    billingUnit: "per forecast cycle",
    heroPrompt: "Every Monday, produce a 13-week rolling cash projection from AR, AP, payroll, and known contracts. Highlight what changed.",
  },
  {
    id: "fin-expense-policy",
    function: "finance",
    name: "Expense policy enforcement",
    tagline: "Out-of-policy submissions flagged with a polite rejection draft citing the clause.",
    killer: false,
    trigger: T.event("ramp.expense.submitted"),
    sources: [src("finance", "ramp"), src("productivity", "notion")],
    action: A("classify", "Flag out-of-policy submissions; draft polite rejection notes with cited policy clause."),
    output: O("email-draft", "finance drafts"),
    approval: APP.draft,
    memory: MEM.org("Knows our policy by reference."),
    sla: "Within 4 hours of submission.",
    priceMonthly: 11900,
    billingUnit: "per expense reviewed",
    heroPrompt: "When an expense is submitted to Ramp or Brex, check it against policy. Flag out-of-policy items and draft a polite rejection with the cited clause.",
  },
  {
    id: "fin-saas-spend",
    function: "finance",
    name: "Vendor & SaaS spend rationalization",
    tagline: "Quarterly sweep — duplicates and unused seats with cancel/downgrade drafts.",
    killer: false,
    trigger: T.quarterly("first week"),
    sources: [src("finance", "ramp"), src("finance", "quickbooks")],
    action: A("reconcile", "Identify duplicate or unused SaaS spend; draft cancellation or downgrade list."),
    output: O("memo", "Quarterly spend memo"),
    approval: APP.draft,
    memory: MEM.perJob("Knows last quarter's recommendations."),
    sla: "First week of each quarter.",
    priceMonthly: 13900,
    billingUnit: "per dollar saved",
    heroPrompt: "Quarterly: sweep SaaS subscriptions. Identify duplicates and unused seats. Produce a cancellation/downgrade list for approval.",
  },
  {
    id: "fin-pricing-impact",
    function: "finance",
    name: "Pricing-change impact model",
    tagline: "Proposed pricing → winners/losers/revenue-delta against current base.",
    killer: false,
    trigger: T.manual(),
    sources: [src("finance", "stripe"), src("crm", "hubspot")],
    action: A("summarize", "Run proposed pricing against the current base; produce winners/losers/revenue-delta memo."),
    output: O("memo", "Pricing-impact memo"),
    approval: APP.draft,
    memory: MEM.perJob("Save prior pricing scenarios."),
    sla: "Within 4 hours.",
    priceMonthly: 14900,
    billingUnit: "per scenario modeled",
    heroPrompt: "Given a proposed pricing change, run it against the current customer base. Produce a winners/losers/revenue-delta memo.",
  },
  {
    id: "fin-sales-tax",
    function: "finance",
    name: "Sales-tax filing prep",
    tagline: "State-by-state nexus prep with founder sign-off.",
    killer: false,
    trigger: T.monthly("20th", "09:00"),
    sources: [src("finance", "stripe")],
    action: A("reconcile", "Pull state-by-state nexus data, prep TaxJar/Avalara filings, alert founder for sign-off."),
    output: O("memo", "Sales-tax filing package"),
    approval: APP.ask,
    memory: MEM.perJob("Track each state's threshold."),
    sla: "By the 20th of each month.",
    priceMonthly: 14900,
    billingUnit: "per filing prepared",
    heroPrompt: "Monthly: pull state-by-state nexus data from Stripe. Prep TaxJar or Avalara filings. Alert the founder for sign-off.",
  },
  {
    id: "fin-investor-update",
    function: "finance",
    name: "Investor update assembly",
    tagline: "Monthly KPIs + narrative draft in the wins/asks/lowlights template.",
    killer: false,
    trigger: T.monthly("1st", "10:00"),
    sources: [src("finance", "stripe"), src("crm", "hubspot"), src("telemetry", "mixpanel")],
    action: A("draft", "Pull KPIs, draft narrative in the wins/asks/lowlights template."),
    output: O("memo", "Investor update draft"),
    approval: APP.draft,
    memory: MEM.org("Maintains the running storyline."),
    sla: "By the 5th of each month.",
    priceMonthly: 17900,
    billingUnit: "per update drafted",
    heroPrompt: "Each month, pull KPIs and draft the investor update narrative in our wins/asks/lowlights template. Queue for founder edits.",
  },
  {
    id: "fin-rd-credit",
    function: "finance",
    name: "R&D credit documentation",
    tagline: "Continuous engineering activity capture → annual package for accountant.",
    killer: false,
    trigger: T.weekly("Friday", "17:00"),
    sources: [src("productivity", "github"), src("productivity", "notion"), src("calendar", "gcal")],
    action: A("classify", "File engineering commits and meeting notes that map to qualifying R&D activity."),
    output: O("table", "R&D activity log"),
    approval: APP.auto,
    memory: MEM.perJob("Track classification over time."),
    sla: "Weekly Friday roll-up.",
    priceMonthly: 11900,
    billingUnit: "per period documented",
    heroPrompt: "Each Friday, classify the week's engineering commits and meeting notes that map to qualifying R&D activity. Produce the annual package by year-end.",
  },
];

/* ============================== LEGAL (10) ============================== */
const LEGAL: JobBlueprint[] = [
  {
    id: "legal-nda-redline",
    function: "legal",
    name: "NDA / MSA first-pass redline",
    tagline: "Counterparty contract → playbook-compared redline with reasoning per change.",
    killer: true,
    trigger: T.inbox("legal@ — contract attachment"),
    sources: [src("files", "pdf"), src("productivity", "gdocs")],
    action: A("draft", "Compare against the company playbook; produce a redline with comment justification per change."),
    output: O("memo", "Marked-up contract + notes"),
    approval: APP.draft,
    memory: MEM.org("Learns the playbook over time."),
    sla: "Within 24 hours.",
    priceMonthly: 39900,
    billingUnit: "per contract reviewed",
    heroPrompt: "When a counterparty NDA or MSA lands, compare against our playbook. Produce a redline with a comment justifying every change.",
  },
  {
    id: "legal-contract-abstract",
    function: "legal",
    name: "Contract abstraction",
    tagline: "Every executed agreement → extracted term/renewal/cap/jurisdiction in a register.",
    killer: false,
    trigger: T.event("docusign.contract.executed"),
    sources: [src("files", "pdf"), src("productivity", "notion")],
    action: A("classify", "Extract term, renewal, auto-renew clause, liability cap, jurisdiction into a register."),
    output: O("table", "Contract register"),
    approval: APP.auto,
    memory: MEM.org("Maintains the register."),
    sla: "Within 4 hours of execution.",
    priceMonthly: 14900,
    billingUnit: "per contract abstracted",
    heroPrompt: "When a contract is executed, extract term, renewal date, auto-renew language, liability cap, and jurisdiction. Add to the contract register.",
  },
  {
    id: "legal-renewal-cal",
    function: "legal",
    name: "Renewal & auto-renewal calendar",
    tagline: "90-day-out surfacing of every renewal with recommended action.",
    killer: false,
    trigger: T.weekly("Monday", "08:00"),
    sources: [src("productivity", "notion")],
    action: A("monitor", "Surface all renewal triggers 90 days out with a recommend-action line."),
    output: O("memo", "Renewal calendar update"),
    approval: APP.auto,
    memory: MEM.perJob("Track action taken per renewal."),
    sla: "Monday by 9:00 AM.",
    priceMonthly: 9900,
    billingUnit: "per renewal surfaced",
    heroPrompt: "Each Monday, surface every contract renewal that's 90 days out. Recommend an action: renew, renegotiate, cancel.",
  },
  {
    id: "legal-policy-drift",
    function: "legal",
    name: "Privacy policy & ToS drift",
    tagline: "Product changes → policy clauses needing updates flagged.",
    killer: false,
    trigger: T.event("product.subprocessor.added"),
    sources: [src("productivity", "github"), src("productivity", "notion")],
    action: A("monitor", "When the product changes (new subprocessor, new data type), flag policy text needing update."),
    output: O("memo", "Policy drift alert"),
    approval: APP.draft,
    memory: MEM.org("Knows our policy structure."),
    sla: "Within 24 hours of change.",
    priceMonthly: 13900,
    billingUnit: "per drift caught",
    heroPrompt: "When the product adds a subprocessor, data type, or feature affecting policy, flag the policy clauses needing update.",
  },
  {
    id: "legal-security-q-respond",
    function: "legal",
    name: "Security questionnaire response",
    tagline: "Mirror of sales-side RFP automation, from the buyer's angle.",
    killer: false,
    trigger: T.manual(),
    sources: [src("files", "xlsx"), src("productivity", "notion")],
    action: A("draft", "Match each question to the prior-answer KB; auto-fill where confident; flag the rest."),
    output: O("memo", "Filled questionnaire + open items"),
    approval: APP.draft,
    memory: MEM.org("Grows the answer playbook over time."),
    sla: "Within 24 hours.",
    priceMonthly: 24900,
    billingUnit: "per questionnaire completed",
    heroPrompt: "Given a vendor security questionnaire, match each question to our knowledge base, auto-fill at high confidence, and flag the rest for human input.",
  },
  {
    id: "legal-dsar",
    function: "legal",
    name: "Data deletion / DSAR handling",
    tagline: "privacy@ email → verification flow + data collection + drafted response.",
    killer: false,
    trigger: T.inbox("privacy@ — DSAR request"),
    sources: [src("inbox", "gmail"), src("crm", "hubspot"), src("finance", "stripe")],
    action: A("coordinate", "Run verification flow; collect data from each system; draft the response."),
    output: O("email-draft", "legal drafts"),
    approval: APP.ask,
    memory: MEM.perTarget("Track requester history."),
    sla: "Within 5 business days.",
    priceMonthly: 14900,
    billingUnit: "per request handled",
    heroPrompt: "When a DSAR or data deletion request arrives at privacy@, run the verification flow, collect data from each system, and draft the response.",
  },
  {
    id: "legal-trademark-watch",
    function: "legal",
    name: "Trademark & cease-and-desist watch",
    tagline: "USPTO + brand mentions monitored; alert with draft response when warranted.",
    killer: false,
    trigger: T.daily("06:00"),
    sources: [src("web", "web"), src("web", "rss")],
    action: A("monitor", "Watch USPTO and brand mentions for confusable marks; alert with a draft response."),
    output: O("memo", "Brand-watch alert"),
    approval: APP.draft,
    memory: MEM.org("Tracks brand portfolio."),
    sla: "Daily 7:00 AM.",
    priceMonthly: 9900,
    billingUnit: "per match flagged",
    heroPrompt: "Daily monitor USPTO trademark filings and brand mentions. Alert with a draft response when a confusable mark warrants action.",
  },
  {
    id: "legal-offer-letter",
    function: "legal",
    name: "Employment offer-letter generation",
    tagline: "Role + comp + start date → template offer + DocuSign routing.",
    killer: true,
    trigger: T.event("greenhouse.offer.approved"),
    sources: [src("people", "greenhouse"), src("productivity", "gdocs")],
    action: A("draft", "Draft the offer letter from template, file in DocuSign, route for signature."),
    output: O("ticket", "DocuSign envelope"),
    approval: APP.draft,
    memory: MEM.stateless,
    sla: "Within 1 hour of offer approval.",
    priceMonthly: 9900,
    billingUnit: "per offer drafted",
    heroPrompt: "When a Greenhouse offer is approved, draft the offer letter from our template. File in DocuSign and route for signature.",
  },
  {
    id: "legal-litigation-hold",
    function: "legal",
    name: "Litigation-hold inventory",
    tagline: "Hold declared → custodians identified, data frozen, chain documented.",
    killer: false,
    trigger: T.manual(),
    sources: [src("people", "rippling"), src("productivity", "gdrive"), src("inbox", "gmail")],
    action: A("coordinate", "Identify custodians, freeze data, document chain."),
    output: O("memo", "Hold inventory"),
    approval: APP.ask,
    memory: MEM.perJob("Maintain the hold ledger."),
    sla: "Within 24 hours of declaration.",
    priceMonthly: 17900,
    billingUnit: "per hold managed",
    heroPrompt: "When a litigation hold is declared, identify custodians across systems, freeze their data, and document the chain of custody.",
  },
  {
    id: "legal-compliance-evidence",
    function: "legal",
    name: "Compliance evidence collection",
    tagline: "Continuous SOC2/ISO evidence harvesting into the audit folder.",
    killer: false,
    trigger: T.daily("23:00"),
    sources: [src("productivity", "github"), src("productivity", "linear"), src("people", "rippling")],
    action: A("classify", "Assemble screenshots, attestations, ticket evidence into the audit folder."),
    output: O("table", "Audit evidence folder"),
    approval: APP.auto,
    memory: MEM.perJob("Track evidence completeness."),
    sla: "Daily nightly.",
    priceMonthly: 17900,
    billingUnit: "per evidence item captured",
    heroPrompt: "Nightly, harvest SOC2/ISO evidence: screenshots, policy attestations, ticket evidence. File into the audit folder.",
  },
];

/* =============================== PEOPLE (10) ============================ */
const PEOPLE: JobBlueprint[] = [
  {
    id: "people-jd",
    function: "people",
    name: "Job description & rubric generation",
    tagline: "Role idea → JD + rubric + first-screen questions + take-home brief.",
    killer: true,
    trigger: T.manual(),
    sources: [src("productivity", "notion"), src("people", "rippling")],
    action: A("draft", "Draft JD + scoring rubric + first-screen questions + take-home brief, calibrated against current comp bands."),
    output: O("memo", "JD package"),
    approval: APP.draft,
    memory: MEM.org("Knows our role taxonomy and bands."),
    sla: "Within 4 hours.",
    priceMonthly: 17900,
    billingUnit: "per JD package",
    heroPrompt: "Given a role idea, draft the JD, scoring rubric, first-screen questions, and take-home brief — calibrated against our current comp bands.",
  },
  {
    id: "people-interview-sched",
    function: "people",
    name: "Interview scheduling coordination",
    tagline: "Multi-interviewer + candidate calendars → invites with prep docs.",
    killer: false,
    trigger: T.event("greenhouse.candidate.advanced"),
    sources: [src("calendar", "gcal"), src("people", "greenhouse")],
    action: A("coordinate", "Across multiple interviewers' calendars and the candidate's availability, find slots, send invites, share prep doc per interviewer."),
    output: O("ticket", "Calendar invites"),
    approval: APP.auto,
    memory: MEM.perTarget("Track each interviewer's load."),
    sla: "Within 2 hours of advance.",
    priceMonthly: 12900,
    billingUnit: "per loop scheduled",
    heroPrompt: "When a candidate advances, coordinate calendars across interviewers and the candidate. Send invites with per-interviewer prep docs.",
  },
  {
    id: "people-reference-checks",
    function: "people",
    name: "Reference-check synthesis",
    tagline: "3 reference interviews → structured summary with themes and risk flags.",
    killer: false,
    trigger: T.manual(),
    sources: [src("files", "loom"), src("productivity", "notion")],
    action: A("summarize", "Produce a structured summary with consistent themes and risk flags."),
    output: O("memo", "Reference synthesis"),
    approval: APP.draft,
    memory: MEM.stateless,
    sla: "Within 24 hours of last reference.",
    priceMonthly: 9900,
    billingUnit: "per synthesis",
    heroPrompt: "Given 3 reference interview notes, produce a structured summary with consistent themes and risk flags.",
  },
  {
    id: "people-onboarding-plan",
    function: "people",
    name: "Onboarding plan generator",
    tagline: "Per new hire: 30/60/90 plan tied to role + manager + buddy, scheduled out.",
    killer: false,
    trigger: T.event("greenhouse.hire.signed"),
    sources: [src("people", "greenhouse"), src("productivity", "notion"), src("calendar", "gcal")],
    action: A("draft", "Produce a 30/60/90 plan tied to role/manager/buddy, scheduled in Notion or Asana."),
    output: O("memo", "Onboarding plan"),
    approval: APP.draft,
    memory: MEM.org("Maintains role templates."),
    sla: "Within 24 hours of signed offer.",
    priceMonthly: 12900,
    billingUnit: "per plan generated",
    heroPrompt: "When a new hire signs, produce their 30/60/90 plan tied to role, manager, and buddy. Schedule it in Notion or Asana.",
  },
  {
    id: "people-perf-review",
    function: "people",
    name: "Performance-review prep",
    tagline: "Per report: peer feedback + self-eval + manager notes + project outcomes drafted.",
    killer: false,
    trigger: T.quarterly("two weeks before review cycle"),
    sources: [src("productivity", "notion"), src("productivity", "github"), src("calendar", "gcal")],
    action: A("draft", "Assemble peer feedback, self-eval, manager notes, project outcomes into a draft review."),
    output: O("memo", "Review draft"),
    approval: APP.draft,
    memory: MEM.perTarget("Track each report's trajectory."),
    sla: "Two weeks before cycle.",
    priceMonthly: 17900,
    billingUnit: "per review drafted",
    heroPrompt: "Quarterly: per report, assemble peer feedback, self-eval, manager notes, and project outcomes into a draft review.",
  },
  {
    id: "people-pto-coverage",
    function: "people",
    name: "PTO & coverage planning",
    tagline: "Coverage gaps for critical functions flagged with swap proposals.",
    killer: false,
    trigger: T.weekly("Friday", "17:00"),
    sources: [src("calendar", "gcal"), src("people", "rippling")],
    action: A("monitor", "Watch PTO calendar; flag coverage gaps for critical functions; draft swap proposals."),
    output: O("memo", "Weekly coverage memo"),
    approval: APP.auto,
    memory: MEM.perJob("Track critical-function coverage."),
    sla: "Friday by 6:00 PM.",
    priceMonthly: 8900,
    billingUnit: "per gap flagged",
    heroPrompt: "Each Friday, monitor PTO calendars. Flag coverage gaps for critical functions next week. Draft swap proposals.",
  },
  {
    id: "people-comp-bench",
    function: "people",
    name: "Comp-band benchmarking",
    tagline: "Quarterly Levels.fyi/Pave/Carta pull → bands updated, out-of-band offers flagged.",
    killer: false,
    trigger: T.quarterly("first week"),
    sources: [src("web", "web"), src("people", "rippling")],
    action: A("research", "Pull comp data, update bands, flag offers outside band."),
    output: O("memo", "Comp-bench update"),
    approval: APP.draft,
    memory: MEM.org("Tracks bands over time."),
    sla: "First week of each quarter.",
    priceMonthly: 11900,
    billingUnit: "per role benchmarked",
    heroPrompt: "Quarterly: pull from Levels.fyi, Pave, Carta. Update comp bands. Flag any offer made outside the band.",
  },
  {
    id: "people-engagement-survey",
    function: "people",
    name: "Engagement survey synthesis",
    tagline: "eNPS/Lattice responses → clustered themes + all-hands talking points.",
    killer: false,
    trigger: T.event("survey.cycle.closed"),
    sources: [src("productivity", "notion")],
    action: A("cluster", "Process responses, cluster themes, draft all-hands talking points."),
    output: O("memo", "Survey synthesis"),
    approval: APP.draft,
    memory: MEM.perJob("Track theme drift cycle over cycle."),
    sla: "Within 5 business days of cycle close.",
    priceMonthly: 12900,
    billingUnit: "per cycle synthesized",
    heroPrompt: "When an engagement survey closes, cluster responses by theme. Draft the all-hands talking points and the founder's response.",
  },
  {
    id: "people-1on1-agenda",
    function: "people",
    name: "1:1 agenda assistant",
    tagline: "Pre-meeting: 2 weeks of Slack/PR/ticket activity → 3 suggested topics.",
    killer: false,
    trigger: T.event("gcal.event.upcoming.30min"),
    sources: [src("chat", "slack"), src("productivity", "github"), src("productivity", "linear")],
    action: A("summarize", "Pull last 2 weeks of activity for both parties. Suggest 3 topics."),
    output: O("slack", "DM to both parties"),
    approval: APP.auto,
    memory: MEM.perTarget("Avoid re-suggesting topics."),
    sla: "30 minutes before each 1:1.",
    priceMonthly: 7900,
    billingUnit: "per 1:1 prepped",
    heroPrompt: "30 minutes before each 1:1, pull the last 2 weeks of Slack, PR, and ticket activity for both parties. Suggest 3 topics worth discussing.",
  },
  {
    id: "people-burnout-signals",
    function: "people",
    name: "Burnout signals (opt-in)",
    tagline: "Working-hour patterns + latency trends → gentle manager alert.",
    killer: false,
    trigger: T.weekly("Monday", "07:00"),
    sources: [src("productivity", "github"), src("chat", "slack"), src("productivity", "linear")],
    action: A("monitor", "Watch hours, latency, late-night commits. Gently alert manager."),
    output: O("slack", "manager DM"),
    approval: APP.draft,
    memory: MEM.perTarget("Track each opt-in person."),
    sla: "Weekly.",
    priceMonthly: 11900,
    billingUnit: "per signal raised",
    heroPrompt: "For opt-in team members, monitor working-hour patterns, ticket-resolution latency, and late-night commits. Gently alert their manager when patterns warrant.",
  },
];

/* =============================== IT (10) ================================ */
const IT: JobBlueprint[] = [
  {
    id: "it-access-review",
    function: "it",
    name: "Access review & least-privilege sweep",
    tagline: "Quarterly: every SaaS, every user, every role — flag stale / over-privileged.",
    killer: true,
    trigger: T.quarterly("first week"),
    sources: [src("productivity", "github"), src("people", "rippling"), src("chat", "slack")],
    action: A("reconcile", "Enumerate users and roles per SaaS; flag stale / over-privileged / outside-tenure; draft remediation tickets."),
    output: O("table", "Access review sheet"),
    approval: APP.draft,
    memory: MEM.perJob("Track remediation status."),
    sla: "First week of each quarter.",
    priceMonthly: 24900,
    billingUnit: "per finding surfaced",
    heroPrompt: "Quarterly: enumerate users and roles across every SaaS tool. Flag stale, over-privileged, or post-tenure access. Draft remediation tickets.",
  },
  {
    id: "it-phish-triage",
    function: "it",
    name: "Phishing-report triage",
    tagline: "phish@ → classification + VirusTotal check + user reply + ticket if real.",
    killer: true,
    trigger: T.inbox("phish@ — forwarded message"),
    sources: [src("inbox", "gmail"), src("web", "web")],
    action: A("classify", "Classify; check URLs in VirusTotal/urlscan; draft user reply; file ticket if real."),
    output: O("ticket", "IT queue"),
    approval: APP.draft,
    memory: MEM.perJob("Track each user's report history."),
    sla: "Within 30 minutes.",
    priceMonthly: 14900,
    billingUnit: "per report triaged",
    heroPrompt: "When a user forwards to phish@, classify, check URLs in VirusTotal and urlscan, draft a reply to the user, and file a ticket if the threat is real.",
  },
  {
    id: "it-provisioning",
    function: "it",
    name: "New-hire provisioning",
    tagline: "Signed offer → Workspace + Slack + GitHub + 1Password + laptop order.",
    killer: false,
    trigger: T.event("greenhouse.hire.signed"),
    sources: [src("people", "greenhouse"), src("productivity", "github"), src("chat", "slack")],
    action: A("coordinate", "Create accounts; file equipment order; notify manager."),
    output: O("ticket", "IT provisioning checklist"),
    approval: APP.ask,
    memory: MEM.stateless,
    sla: "Within 1 business day of signed offer.",
    priceMonthly: 13900,
    billingUnit: "per hire provisioned",
    heroPrompt: "When a new hire signs, provision: Google Workspace, Slack, GitHub, 1Password. File equipment order. Notify manager.",
  },
  {
    id: "it-patch-advisory",
    function: "it",
    name: "Patch & update advisory",
    tagline: "Vendor advisories filtered to your fleet → rollout plan.",
    killer: false,
    trigger: T.daily("07:00"),
    sources: [src("web", "rss"), src("people", "rippling")],
    action: A("monitor", "Watch advisories; identify which apply to the fleet; draft rollout plan."),
    output: O("memo", "Patch advisory"),
    approval: APP.draft,
    memory: MEM.perJob("Track patch coverage."),
    sla: "Daily morning.",
    priceMonthly: 11900,
    billingUnit: "per advisory handled",
    heroPrompt: "Daily monitor Apple, CrowdStrike, and other vendor advisories. Identify which apply to our fleet. Draft a rollout plan.",
  },
  {
    id: "it-endpoint-compliance",
    function: "it",
    name: "Endpoint compliance check",
    tagline: "Weekly: laptops missing encryption, updates, or MDM check-in.",
    killer: false,
    trigger: T.weekly("Friday", "12:00"),
    sources: [src("people", "rippling")],
    action: A("monitor", "Identify non-compliant endpoints; draft user nudges."),
    output: O("table", "Compliance sheet"),
    approval: APP.draft,
    memory: MEM.perTarget("Track each endpoint over time."),
    sla: "Friday by 1:00 PM.",
    priceMonthly: 11900,
    billingUnit: "per endpoint flagged",
    heroPrompt: "Each Friday, identify laptops missing disk encryption, OS updates, or MDM check-in. Draft user nudges for the worst offenders.",
  },
  {
    id: "it-domain-hygiene",
    function: "it",
    name: "Domain & DNS hygiene",
    tagline: "SPF/DKIM/DMARC alignment, cert expirations, dangling DNS.",
    killer: false,
    trigger: T.daily("06:00"),
    sources: [src("web", "url")],
    action: A("monitor", "Watch DNS, certs, dangling records; alert before things break."),
    output: O("alert", "IT Slack DM"),
    approval: APP.auto,
    memory: MEM.perJob("Track each domain's posture."),
    sla: "Daily.",
    priceMonthly: 8900,
    billingUnit: "per issue caught",
    heroPrompt: "Daily check SPF, DKIM, DMARC alignment, certificate expirations, and dangling DNS records. Alert before things break.",
  },
  {
    id: "it-saas-sprawl",
    function: "it",
    name: "SaaS sprawl audit",
    tagline: "SSO logs vs expense records vs official list → shadow IT surfaced.",
    killer: false,
    trigger: T.monthly("1st", "09:00"),
    sources: [src("finance", "ramp"), src("productivity", "notion")],
    action: A("reconcile", "Match SSO logs vs expenses vs the official SaaS list; flag shadow IT."),
    output: O("memo", "Shadow IT report"),
    approval: APP.draft,
    memory: MEM.perJob("Track known shadow tools."),
    sla: "By the 2nd of each month.",
    priceMonthly: 12900,
    billingUnit: "per shadow tool found",
    heroPrompt: "Monthly: match SSO logs against expense records and the official SaaS list. Flag shadow IT.",
  },
  {
    id: "it-backup-verify",
    function: "it",
    name: "Backup verification",
    tagline: "Weekly success check + quarterly restore test.",
    killer: false,
    trigger: T.weekly("Sunday", "23:00"),
    sources: [src("productivity", "github")],
    action: A("monitor", "Check that backups for critical systems succeeded; quarterly restore test."),
    output: O("alert", "IT Slack channel"),
    approval: APP.auto,
    memory: MEM.perJob("Track backup history."),
    sla: "Weekly check + quarterly drill.",
    priceMonthly: 8900,
    billingUnit: "per backup verified",
    heroPrompt: "Each Sunday night, verify backups for every critical system succeeded. Quarterly, run a restore test.",
  },
  {
    id: "it-postmortem-draft",
    function: "it",
    name: "Incident post-mortem first-draft",
    tagline: "Statuspage event + Slack channel transcript → blameless post-mortem.",
    killer: false,
    trigger: T.event("incident.resolved"),
    sources: [src("chat", "slack"), src("web", "url")],
    action: A("draft", "Given the incident channel transcript and Statuspage events, draft a blameless post-mortem."),
    output: O("memo", "Post-mortem draft"),
    approval: APP.draft,
    memory: MEM.perJob("Tracks incident patterns."),
    sla: "Within 24 hours of resolution.",
    priceMonthly: 12900,
    billingUnit: "per post-mortem drafted",
    heroPrompt: "After an incident resolves, draft a blameless post-mortem from the Slack channel transcript and Statuspage events.",
  },
  {
    id: "it-breach-impact",
    function: "it",
    name: "Vendor breach impact memo",
    tagline: "Vendor announces breach → are we affected, which data, what action.",
    killer: false,
    trigger: T.event("security.vendor.breach.announced"),
    sources: [src("web", "rss"), src("productivity", "notion")],
    action: A("research", "Identify whether we're affected, which data, what action to take."),
    output: O("memo", "Breach impact memo"),
    approval: APP.draft,
    memory: MEM.org("Knows our vendor map."),
    sla: "Within 4 hours of announcement.",
    priceMonthly: 11900,
    billingUnit: "per breach analyzed",
    heroPrompt: "When a vendor announces a breach, determine whether we're affected, which data is implicated, and what action to take.",
  },
];

/* ============================= PRODUCT (10) ============================= */
const PRODUCT: JobBlueprint[] = [
  {
    id: "prod-feedback-cluster",
    function: "product",
    name: "Feature-request clustering",
    tagline: "Intercom + Gong + Slack + GitHub → 20 themes ranked by weighted demand.",
    killer: true,
    trigger: T.weekly("Monday", "07:00"),
    sources: [src("inbox", "intercom"), src("chat", "slack"), src("productivity", "github"), src("files", "loom")],
    action: A("cluster", "Aggregate across channels; cluster into 20 themes; rank by weighted demand."),
    output: O("memo", "Feature clusters memo"),
    approval: APP.auto,
    memory: MEM.perJob("Track theme trajectory."),
    sla: "Monday by 8:00 AM.",
    priceMonthly: 22900,
    billingUnit: "per theme surfaced",
    heroPrompt: "Each Monday, aggregate feature requests from Intercom, Gong, Slack, and GitHub. Cluster into 20 themes ranked by weighted demand.",
  },
  {
    id: "prod-competitor-releases",
    function: "product",
    name: "Competitor release tracking",
    tagline: "Weekly memo: what they shipped, why it matters.",
    killer: true,
    trigger: T.weekly("Friday", "12:00"),
    sources: [src("web", "url"), src("web", "rss"), src("web", "web")],
    action: A("monitor", "Scrape competitor changelogs, blogs, releases, social; deliver a 'what they shipped, why it matters' memo."),
    output: O("memo", "Competitor release memo"),
    approval: APP.auto,
    memory: MEM.perJob("Track competitor cadences."),
    sla: "Friday by 1:00 PM.",
    priceMonthly: 17900,
    billingUnit: "per memo published",
    heroPrompt: "Each Friday, scrape competitor changelogs, blogs, releases, and social. Produce a memo: what they shipped, why it matters, how we should respond.",
  },
  {
    id: "prod-interview-recruit",
    function: "product",
    name: "User-interview recruit + synthesis",
    tagline: "Segment criteria → recruit + schedule + transcribe + memo.",
    killer: false,
    trigger: T.manual(),
    sources: [src("crm", "hubspot"), src("telemetry", "mixpanel"), src("calendar", "calendly")],
    action: A("coordinate", "Identify users matching segment criteria, schedule, prep, transcribe, synthesize."),
    output: O("memo", "Research synthesis"),
    approval: APP.draft,
    memory: MEM.perJob("Don't re-recruit recent participants."),
    sla: "Initial recruit within 48 hours.",
    priceMonthly: 19900,
    billingUnit: "per interview cycle",
    heroPrompt: "Given a user segment, recruit matching candidates from CRM and product telemetry. Schedule, transcribe, and synthesize into a memo.",
  },
  {
    id: "prod-bug-dedupe",
    function: "product",
    name: "Bug-report deduplication & routing",
    tagline: "Incoming bugs → matched against open issues, routed, acknowledged.",
    killer: false,
    trigger: T.event("intercom.bug-report.received"),
    sources: [src("inbox", "intercom"), src("productivity", "linear"), src("productivity", "github")],
    action: A("classify", "Match against open issues, route to the right team, draft acknowledgment."),
    output: O("ticket", "Linear · routed"),
    approval: APP.draft,
    memory: MEM.perJob("Track every reported bug."),
    sla: "Within 15 minutes.",
    priceMonthly: 12900,
    billingUnit: "per bug triaged",
    heroPrompt: "When a bug report arrives, match it against open Linear/GitHub issues. Route to the right team. Draft acknowledgment to the reporter.",
  },
  {
    id: "prod-release-notes",
    function: "product",
    name: "Release notes drafting",
    tagline: "Merged PRs since last release → audience-tuned release notes.",
    killer: false,
    trigger: T.event("github.tag.created"),
    sources: [src("productivity", "github")],
    action: A("draft", "Draft user-facing release notes from merged PRs; tune by audience (technical / non-technical)."),
    output: O("memo", "Release notes draft"),
    approval: APP.draft,
    memory: MEM.org("Keeps voice consistent."),
    sla: "Within 1 hour of tag.",
    priceMonthly: 9900,
    billingUnit: "per release drafted",
    heroPrompt: "When a release tag is created, draft user-facing release notes from the merged PRs since the last release. Tune by audience.",
  },
  {
    id: "prod-dogfood-report",
    function: "product",
    name: "Dogfood usage report",
    tagline: "Internal team adoption: who's using it, who isn't, what they say.",
    killer: false,
    trigger: T.weekly("Friday", "16:00"),
    sources: [src("telemetry", "mixpanel"), src("chat", "slack")],
    action: A("summarize", "Weekly memo of internal adoption with friction comments."),
    output: O("memo", "Dogfood report"),
    approval: APP.auto,
    memory: MEM.perJob("Track adoption trajectory."),
    sla: "Friday by 5:00 PM.",
    priceMonthly: 7900,
    billingUnit: "per report delivered",
    heroPrompt: "Each Friday, produce a dogfood usage report: who's using the internal product, who isn't, and what friction is being voiced.",
  },
  {
    id: "prod-roadmap-sync",
    function: "product",
    name: "Roadmap-doc maintenance",
    tagline: "Public roadmap auto-synced with engineering reality.",
    killer: false,
    trigger: T.weekly("Wednesday", "10:00"),
    sources: [src("productivity", "linear"), src("productivity", "notion")],
    action: A("reconcile", "Keep the public roadmap synced with engineering sprints; flag drift."),
    output: O("memo", "Roadmap drift report"),
    approval: APP.draft,
    memory: MEM.perJob("Track historical drift."),
    sla: "Wednesday by 11:00 AM.",
    priceMonthly: 9900,
    billingUnit: "per drift caught",
    heroPrompt: "Each Wednesday, sync the public roadmap with engineering's actual sprint plan. Flag drift in both directions.",
  },
  {
    id: "prod-flag-cleanup",
    function: "product",
    name: "Feature-flag cleanup",
    tagline: "Stale flags identified with removal-PR drafts ready.",
    killer: false,
    trigger: T.monthly("1st", "09:00"),
    sources: [src("productivity", "github")],
    action: A("monitor", "Identify flags 100/0 for >30 days; draft removal PRs."),
    output: O("ticket", "Eng queue · flag cleanup"),
    approval: APP.draft,
    memory: MEM.perJob("Track each flag's lifecycle."),
    sla: "First week of each month.",
    priceMonthly: 8900,
    billingUnit: "per flag retired",
    heroPrompt: "Monthly: identify feature flags 100/0 for >30 days. Draft removal PRs ready for engineering review.",
  },
  {
    id: "prod-pricing-ab",
    function: "product",
    name: "Pricing-page A/B suggestions",
    tagline: "Conversion + competitor data + interview notes → 2–3 experiments.",
    killer: false,
    trigger: T.quarterly("first week"),
    sources: [src("telemetry", "ga4"), src("crm", "hubspot"), src("web", "web")],
    action: A("research", "Compare conversion + competitor pricing + interview notes; propose 2-3 experiments."),
    output: O("memo", "Pricing experiments memo"),
    approval: APP.draft,
    memory: MEM.perJob("Track prior experiments."),
    sla: "First week of each quarter.",
    priceMonthly: 13900,
    billingUnit: "per experiment proposed",
    heroPrompt: "Quarterly: compare our conversion data, competitor pricing, and customer interview notes. Propose 2-3 pricing-page experiments.",
  },
  {
    id: "prod-cab-prep",
    function: "product",
    name: "Customer-advisory-board prep",
    tagline: "Agenda + pre-reads + attendee context + post-meeting action items.",
    killer: false,
    trigger: T.quarterly("two weeks before CAB"),
    sources: [src("crm", "hubspot"), src("productivity", "notion")],
    action: A("draft", "Assemble agenda, pre-reads, attendee context. After: action items."),
    output: O("memo", "CAB package"),
    approval: APP.draft,
    memory: MEM.perJob("Track each CAB cycle's themes."),
    sla: "Two weeks before CAB.",
    priceMonthly: 14900,
    billingUnit: "per CAB cycle",
    heroPrompt: "Two weeks before each Customer Advisory Board, assemble the agenda, pre-reads, attendee context. After the meeting, draft action items.",
  },
];

/* ============================ FOUNDER (10) ============================== */
const FOUNDER: JobBlueprint[] = [
  {
    id: "founder-inbox-zero",
    function: "founder",
    name: "Inbox-zero assistant",
    tagline: "Triage into needs-you / delegate / FYI / no-action; draft the bottom three.",
    killer: true,
    trigger: T.daily("07:00"),
    sources: [src("inbox", "gmail")],
    action: A("classify", "Triage the founder inbox into four buckets; draft replies for delegate/FYI/no-action."),
    output: O("email-draft", "founder drafts"),
    approval: APP.draft,
    memory: MEM.org("Knows the founder's voice and preferences."),
    sla: "By 7:30 AM daily.",
    priceMonthly: 29900,
    billingUnit: "per email triaged",
    heroPrompt: "Each morning, triage the founder's inbox into 'needs you', 'can delegate', 'FYI', 'no action'. Draft replies for the bottom three buckets in the founder's voice.",
  },
  {
    id: "founder-daily-brief",
    function: "founder",
    name: "Daily morning brief",
    tagline: "Calendar context + pipeline highlights + fires + 3 most important emails.",
    killer: true,
    trigger: T.daily("06:30"),
    sources: [src("calendar", "gcal"), src("crm", "hubspot"), src("inbox", "gmail"), src("chat", "slack")],
    action: A("summarize", "Each meeting with context, pipeline highlights, fires, 3 most important emails awaiting reply."),
    output: O("memo", "Daily founder brief"),
    approval: APP.auto,
    memory: MEM.org("Knows what the founder cares about."),
    sla: "By 7:00 AM daily.",
    priceMonthly: 24900,
    billingUnit: "per daily brief",
    heroPrompt: "Each morning at 7 AM, produce the founder brief: calendar with context per meeting, pipeline highlights, any fire (support, ops, finance), 3 most important emails awaiting reply.",
  },
  {
    id: "founder-cal-defrag",
    function: "founder",
    name: "Calendar defragmentation",
    tagline: "Overlap + low-value recurring meetings + 'no-meeting day' proposals.",
    killer: false,
    trigger: T.weekly("Friday", "16:00"),
    sources: [src("calendar", "gcal")],
    action: A("monitor", "Identify meeting overlap, low-value recurrings, suggest no-meeting-day reshuffles."),
    output: O("memo", "Calendar defrag memo"),
    approval: APP.draft,
    memory: MEM.perJob("Track schedule patterns."),
    sla: "Friday by 5:00 PM.",
    priceMonthly: 9900,
    billingUnit: "per defrag proposal",
    heroPrompt: "Each Friday afternoon, scan the founder's calendar. Identify meeting overlap, low-value recurring meetings, and propose 'no-meeting day' reshuffles.",
  },
  {
    id: "founder-investor-crm",
    function: "founder",
    name: "Investor / advisor relationship CRM",
    tagline: "'Haven't talked in 90 days, here's what's new' outreach drafts.",
    killer: false,
    trigger: T.weekly("Friday", "10:00"),
    sources: [src("inbox", "gmail"), src("crm", "attio")],
    action: A("monitor", "Track interactions; surface stale relationships; draft outreach."),
    output: O("email-draft", "founder drafts"),
    approval: APP.draft,
    memory: MEM.perTarget("Track every investor/advisor interaction."),
    sla: "Friday by 11:00 AM.",
    priceMonthly: 14900,
    billingUnit: "per outreach drafted",
    heroPrompt: "Each Friday, surface investors and advisors the founder hasn't talked to in 90+ days. Draft outreach summarizing what's new and worth sharing.",
  },
  {
    id: "founder-board-prep",
    function: "founder",
    name: "Board-meeting prep",
    tagline: "Metrics + narrative + Q&A cheat-sheet + the 2 hard questions to pre-answer.",
    killer: false,
    trigger: T.quarterly("two weeks before board meeting"),
    sources: [src("finance", "stripe"), src("crm", "hubspot"), src("telemetry", "mixpanel")],
    action: A("draft", "Assemble metrics, draft narrative, prep Q&A cheat-sheet, identify the 2 hard questions to pre-answer."),
    output: O("memo", "Board prep package"),
    approval: APP.draft,
    memory: MEM.perJob("Maintain board-narrative continuity."),
    sla: "Two weeks before the meeting.",
    priceMonthly: 49900,
    billingUnit: "per board prep",
    heroPrompt: "Quarterly: two weeks before board, assemble metrics, draft the narrative, prep the Q&A cheat-sheet, and identify the 2 hard questions to pre-answer.",
  },
  {
    id: "founder-strategic-scan",
    function: "founder",
    name: "Strategic deal-of-the-day scan",
    tagline: "Daily Crunchbase/PitchBook scan for partnership/acquisition/hiring openings.",
    killer: false,
    trigger: T.daily("06:00"),
    sources: [src("web", "crunchbase"), src("web", "rss")],
    action: A("research", "Scan Crunchbase/PitchBook/industry news for partnership/acquisition/hiring opportunities."),
    output: O("memo", "Daily strategic scan"),
    approval: APP.auto,
    memory: MEM.perJob("Track followed leads."),
    sla: "Daily by 6:30 AM.",
    priceMonthly: 17900,
    billingUnit: "per opportunity surfaced",
    heroPrompt: "Daily scan Crunchbase, PitchBook, and industry news. Surface any partnership, acquisition, or hiring opportunity worth the founder's 30 seconds.",
  },
  {
    id: "founder-reading-list",
    function: "founder",
    name: "Reading-list curation",
    tagline: "5 substacks/podcasts/papers per week, only the ones worth your time.",
    killer: false,
    trigger: T.weekly("Sunday", "18:00"),
    sources: [src("web", "rss")],
    action: A("research", "Curate '5 things worth your time' from the founder's interest graph."),
    output: O("memo", "Sunday reading list"),
    approval: APP.auto,
    memory: MEM.org("Learns the founder's evolving interest graph."),
    sla: "Sunday evening.",
    priceMonthly: 9900,
    billingUnit: "per weekly list",
    heroPrompt: "Each Sunday evening, curate 5 substacks, podcasts, or papers worth the founder's time this week. Annotate why each one matters.",
  },
  {
    id: "founder-goal-tracker",
    function: "founder",
    name: "Personal goal tracker",
    tagline: "Weekly check-in on declared quarterly goals; surface drift.",
    killer: false,
    trigger: T.weekly("Friday", "17:00"),
    sources: [src("productivity", "notion"), src("calendar", "gcal")],
    action: A("monitor", "Weekly check-in on quarterly goals; surface drift."),
    output: O("slack", "founder DM"),
    approval: APP.auto,
    memory: MEM.perJob("Track each goal week over week."),
    sla: "Friday evening.",
    priceMonthly: 7900,
    billingUnit: "per check-in",
    heroPrompt: "Each Friday evening, check the founder's declared quarterly goals against the week's activity. Surface drift gently in DM.",
  },
  {
    id: "founder-content",
    function: "founder",
    name: "Founder content drafting",
    tagline: "Loom rants + voice memos + Slack threads → LinkedIn/blog drafts in your voice.",
    killer: false,
    trigger: T.manual(),
    sources: [src("files", "loom"), src("chat", "slack"), src("productivity", "gdocs")],
    action: A("draft", "Turn the founder's spoken/written drafts into LinkedIn/blog posts in their voice."),
    output: O("memo", "Content draft"),
    approval: APP.draft,
    memory: MEM.org("Learns the founder's writing voice over time."),
    sla: "Within 2 hours of source.",
    priceMonthly: 17900,
    billingUnit: "per draft delivered",
    heroPrompt: "Turn the founder's Loom rants, voice memos, and Slack threads into draft LinkedIn or blog posts in their voice.",
  },
  {
    id: "founder-crisis-comms",
    function: "founder",
    name: "Crisis-comms first-draft",
    tagline: "Outage / PR moment / key departure → internal + external drafts in 15 min.",
    killer: false,
    trigger: T.manual(),
    sources: [src("chat", "slack"), src("productivity", "gdocs")],
    action: A("draft", "Draft internal + external comms in the founder's known voice."),
    output: O("memo", "Comms drafts"),
    approval: APP.ask,
    memory: MEM.org("Knows the company's voice for hard moments."),
    sla: "Within 15 minutes.",
    priceMonthly: 14900,
    billingUnit: "per crisis handled",
    heroPrompt: "When something breaks (outage, PR moment, key departure), draft internal + external comms in the founder's voice within 15 minutes.",
  },
];

/* =========================== Catalog union ============================== */

export const JOB_CATALOG: ReadonlyArray<JobBlueprint> = [
  ...SALES,
  ...MARKETING,
  ...CS,
  ...OPS,
  ...FINANCE,
  ...LEGAL,
  ...PEOPLE,
  ...IT,
  ...PRODUCT,
  ...FOUNDER,
];

export function getJobBlueprint(id: string): JobBlueprint | undefined {
  return JOB_CATALOG.find((j) => j.id === id);
}

export function jobsByFunction(fid: FunctionId): JobBlueprint[] {
  return JOB_CATALOG.filter((j) => j.function === fid);
}

export function killerJobs(): JobBlueprint[] {
  return JOB_CATALOG.filter((j) => j.killer);
}
